### ISSUE TITLE
Add Community links

### ISSUE THREAD

**Issue by frju365** [spring1944/spring1944.github.io#8]
My goal is to add community link : 
- [x] Forum link : https://github.com/spring1944/spring1944.github.io/pull/7
- [x] Matrix
- [x] IRC

**Comment by sanguinariojoe** [comment]
See https://github.com/spring1944/spring1944.github.io/commit/37948cbc0ce4e8fa8146e05cb77c2c17a246136e

**Comment by frju365** [comment]
Can we change is to a more nice menu (anyway, thanks, I was doin it but it's exactly what I wanted to do). I just want to avoid clicking.

**Comment by sanguinariojoe** [comment]
Then prolly you wanna apply a small javascript

**Comment by frju365** [comment]
indeed.
